### ISSUE TITLE
ImportError: cannot import name 'print_log' from 'mmcv.utils'

### ISSUE THREAD

**Issue by ulmasovjafarbek** [coperception/coperception#45]
I faced this error when running `make test` command. I was able to resolve it by replacing
`# from mmcv.utils import print_log`
with:
`from mmengine import print_log`
in `coperception/coperception/utils/mean_app.py`

Full error message:
```
(coperception) your_user@host:~/coperception/tools/det$ make test com=upperbound
python test_codet.py \
--data /home/your_user/data/V2X-Sim-2.0-mini/det/test \
--com upperbound \
--resume logs/upperbound/with_rsu/epoch_100.pth \
--tracking \
--logpath logs \
--apply_late_fusion 0 \
--visualization 0 \
--rsu 1
Traceback (most recent call last):
  File "test_codet.py", line 13, in <module>
    from coperception.utils.mean_ap import eval_map
  File "/home/your_user/coperception/coperception/utils/mean_ap.py", line 3, in <module>
    from mmcv.utils import print_log
ImportError: cannot import name 'print_log' from 'mmcv.utils' (/home/your_user/miniconda/envs/coperception/lib/python3.7/site-packages/mmcv/utils/__init__.py)
make: *** [Makefile:106: test] Error 1
```

**Comment by dekunma** [comment]
Thank you for pointing this out! It might be due to OpenMMLab migrating their APIs.

**Comment by ulmasovjafarbek** [comment]
alternatively, installing `mmcv-full==1.5.0` version also works.
