### ISSUE TITLE
Testing model not working

### ISSUE THREAD

**Issue by ulmasovjafarbek** [coperception/coperception#46]
I have tried to run `upperbound` model testing with `make test_no_rsu` and `make test`, but getting the same error. Main error message is `TypeError: forward() missing 1 required positional argument: 'bevs'` in CoDetModule.py. The same error message when I ran with rsu=1 Below is full error message. Let me know if you know the cause or ever faced a similar issue.

I'm downloaded checkpoints for `upperbound` from preprocessed folder. For test folder, I manually divided the dataset.

```
(coperception) jju4@amax:~/coperception/tools/det$ make test_no_rsu com=upperbound
python test_codet.py \
--data /home/jju4/data/V2X-Sim-2.0-mini/det/test \
--com upperbound \
--resume logs/upperbound/no_rsu/epoch_100.pth \
--tracking \
--logpath logs \
--apply_late_fusion 0 \
--visualization 0 \
--rsu 0
Namespace(apply_late_fusion=0, box_com=False, com='upperbound', compress_level=0, data='/home/jju4/data/V2X-Sim-2.0-mini/det/test', gnn_iter_times=3, inference=None, kd_flag=0, kd_weight=100000, layer=3, log=False, logpath='logs', lr=0.001, nepoch=100, num_agent=6, nworker=1, only_v2i=0, pose_noise=0, resume='logs/upperbound/no_rsu/epoch_100.pth', resume_teacher='', rsu=0, tracking=True, visualization=0, warp_flag=0)
device number 4
flag upperbound
The number of val sequences: 100
The number of val sequences: 100
Validation dataset size: 100
Load model from logs/upperbound/no_rsu/epoch_100.pth, at epoch 100
([('/home/jju4/data/V2X-Sim-2.0-mini/det/test/agent1/0_0/0.npy',)], [('/home/jju4/data/V2X-Sim-2.0-mini/det/test/agent2/0_0/0.npy',)], [('/home/jju4/data/V2X-Sim-2.0-mini/det/test/agent3/0_0/0.npy',)], [('/home/jju4/data/V2X-Sim-2.0-mini/det/test/agent4/0_8/0.npy',)], [('/home/jju4/data/V2X-Sim-2.0-mini/det/test/agent5/0_0/0.npy',)])
Traceback (most recent call last):
  File "test_codet.py", line 586, in <module>
    main(args)
  File "/home/jju4/miniconda3/envs/coperception/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "test_codet.py", line 283, in main
    data, 1, num_agent=num_agent
  File "/home/jju4/coperception/coperception/utils/CoDetModule.py", line 431, in predict_all
    bev_seq, trans_matrices, num_all_agents, batch_size=batch_size
  File "/home/jju4/miniconda3/envs/coperception/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jju4/miniconda3/envs/coperception/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/jju4/miniconda3/envs/coperception/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/jju4/miniconda3/envs/coperception/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/home/jju4/miniconda3/envs/coperception/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
TypeError: Caught TypeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/jju4/miniconda3/envs/coperception/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/jju4/miniconda3/envs/coperception/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'bevs'

make: *** [Makefile:117: test_no_rsu] Error 1
```

**Comment by dekunma** [comment]
Hi @ulmasovjafarbek , I freshly cloned the code to my machine but was not able to reproduce your error:
![image](https://github.com/coperception/coperception/assets/53892579/01c0ebb5-c658-4aa8-8b2a-298e51f09549)

Did you make any changes to the code? The line 431 that the output above is referring to is actually line 430:
https://github.com/coperception/coperception/blob/bbe357f529e0c391ae4e3d9ae6d83e8ce906dcc0/coperception/utils/CoDetModule.py#L430

**Comment by ulmasovjafarbek** [comment]
Thank you, this makes it clear.

**Comment by www235-co** [comment]
Hi @ulmasovjafarbek ,I encountered the same problem, but I did not make any changes to the code, how did you solve it

**Comment by PHate99525** [comment]
Hello @www235-co , Same problem. I didn't change any code either. My solution was to change it to keyword argument. But I do not know if there will be other problems.
